name: "Test"
on: [pull_request, push]

jobs:
  minikube-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: opsgang/ga-setup-minikube@v0.1.1
        with:
          minikube-version: 1.4.0
          k8s-version: 1.16.2
      - name: Testing
        run: |
          minikube config set vm-driver kvm2
          minikube config set kubernetes-version=1.16.2
          minikube start
          minikube update-context
          kubectl cluster-info
          kubectl get pods -n kube-system
          pwd
          ls
          echo $PATH
