on: [pull_request, push]

jobs:
  example:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JQ
        run: sudo apt-get install jq
      - name: Install Kubectl Test
        run: chmod +x ./kubectl-test && sudo cp ./kubectl-test /usr/local/bin
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v1.0.1
        with:
          minikube version: "v1.5.2"
          kubernetes version: "v1.16.2"
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify Kubectl Test Plugin
        run: kubectl test --help
      - name: Test
        run: |
          kubectl apply -f tests/job-success.yml
          sleep 10
          kubectl test check

          kubectl apply -f tests/job-failure.yml
          sleep 10
          if kubectl test check ; then
              echo "Second job should fail"
              exit 1
          else
              exit 0
          fi
